name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Обновление раз в сутки
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: omargaly
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Almaty
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_activity: yes
          plugin_activity_limit: 5
